line: cs-cnbd
limit: 1
streamers:
  output/result.mp4:
    copyright: 1
    source: 转载来源
    tid: 171 # 投稿分区
    cover: "input/cover.jpg"
    title: 你想知道马斯克的超级学习法是什么吗？
    desc_format_id: 0
    desc: 学习技能提升
    dolby: 1 # 杜比音效
    lossless_music: 1 # Hi-Res
    dynamic: ""
    subtitle:
      open: 0
      lan: ""
    tag: "学习效率"
    dtime: ~
    open_subtitle: false