line: cs-cnbd
limit: 1
streamers:
  output/result.mp4:
    copyright: 1
    source: 转载来源
    tid: 171 # 投稿分区
    cover: "input/cover.jpg"
    title: 五大平台融合，引爆未来增长
    desc_format_id: 0
    desc: huanyuan-world-mirror
    dolby: 1 # 杜比音效
    lossless_music: 1 # Hi-Res
    dynamic: ""
    subtitle:
      open: 0
      lan: ""
    tag: "海外投资"
    dtime: ~
    open_subtitle: false